/*

 SIMPLEBACKGROUNDMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\jackd\OneDrive\Desktop\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmap2Width 20
#define backgroundmap2Height 18
#define backgroundmap2Bank 0

extern unsigned char backgroundmap2[];

/* End of SIMPLEBACKGROUNDMAP2.H */
